const resList = [
	{
		info: {
			id: '30490',
			name: 'Baskin Robbins - Ice Cream Desserts',
			cloudinaryImageId: '85ccae4e3576f9330af102c46ca85395',
			locality: 'Shakespeare Sarani Road',
			areaName: 'Elgin',
			costForTwo: '₹400 for two',
			cuisines: ['Ice Cream', 'Desserts'],
			avgRating: 4.7,
			veg: true,
			parentId: '5588',
			avgRatingString: '4.7',
			totalRatingsString: '1K+',
			sla: {
				deliveryTime: 30,
				lastMileTravel: 4.5,
				serviceability: 'SERVICEABLE',
				slaString: '30-35 mins',
				lastMileTravelString: '4.5 km',
				iconType: 'ICON_TYPE_EMPTY',
			},
			availability: {
				nextCloseTime: '2024-03-17 03:30:00',
				opened: true,
			},
			badges: {},
			isOpen: true,
			type: 'F',
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			aggregatedDiscountInfoV3: {
				header: '30% OFF',
				subHeader: 'UPTO ₹75',
			},
			differentiatedUi: {
				displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
				differentiatedUiMediaDetails: {
					mediaType: 'ADS_MEDIA_ENUM_IMAGE',
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
			restaurantOfferPresentationInfo: {},
		},
		analytics: {},
		cta: {
			link: 'https://www.swiggy.com/restaurants/baskin-robbins-ice-cream-desserts-shakespeare-sarani-road-elgin-kolkata-30490',
			type: 'WEBLINK',
		},
	},
	{
		info: {
			id: '3071',
			name: 'Jai Hind Dhaba',
			cloudinaryImageId: 'cdbdjcego1vt4reojqiy',
			locality: 'Bhawanipur',
			areaName: 'Bhawanipur',
			costForTwo: '₹500 for two',
			cuisines: [
				'North Indian',
				'Indian',
				'Tandoor',
				'Kebabs',
				'Punjabi',
				'Home Food',
				'Chinese',
			],
			avgRating: 4.5,
			parentId: '1928',
			avgRatingString: '4.5',
			totalRatingsString: '10K+',
			sla: {
				deliveryTime: 31,
				lastMileTravel: 4.5,
				serviceability: 'SERVICEABLE',
				slaString: '30-35 mins',
				lastMileTravelString: '4.5 km',
				iconType: 'ICON_TYPE_EMPTY',
			},
			availability: {
				nextCloseTime: '2024-03-17 05:00:00',
				opened: true,
			},
			badges: {},
			isOpen: true,
			type: 'F',
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			aggregatedDiscountInfoV3: {
				header: '₹75 OFF',
				subHeader: 'ABOVE ₹249',
				discountTag: 'FLAT DEAL',
			},
			differentiatedUi: {
				displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
				differentiatedUiMediaDetails: {
					mediaType: 'ADS_MEDIA_ENUM_IMAGE',
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
			restaurantOfferPresentationInfo: {},
		},
		analytics: {},
		cta: {
			link: 'https://www.swiggy.com/restaurants/jai-hind-dhaba-bhawanipur-kolkata-3071',
			type: 'WEBLINK',
		},
	},
	{
		info: {
			id: '486554',
			name: '6 Ballygunge Place',
			cloudinaryImageId: 'qaeaixdekwcjuecsjsg9',
			areaName: 'New Alipore',
			costForTwo: '₹800 for two',
			cuisines: ['Indian', 'Snacks', 'Sweets', 'Biryani'],
			avgRating: 4.5,
			parentId: '1243',
			avgRatingString: '4.5',
			totalRatingsString: '1K+',
			sla: {
				deliveryTime: 34,
				lastMileTravel: 7.4,
				serviceability: 'SERVICEABLE',
				slaString: '30-35 mins',
				lastMileTravelString: '7.4 km',
				iconType: 'ICON_TYPE_EMPTY',
			},
			availability: {
				nextCloseTime: '2024-03-17 04:00:00',
				opened: true,
			},
			badges: {},
			isOpen: true,
			aggregatedDiscountInfoV2: {},
			type: 'F',
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			differentiatedUi: {
				displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
				differentiatedUiMediaDetails: {
					mediaType: 'ADS_MEDIA_ENUM_IMAGE',
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
			restaurantOfferPresentationInfo: {},
		},
		analytics: {},
		cta: {
			link: 'https://www.swiggy.com/restaurants/6-ballygunge-place-new-alipore-kolkata-486554',
			type: 'WEBLINK',
		},
	},
	{
		info: {
			id: '77719',
			name: 'The Biryani Inc. By EatVerse',
			cloudinaryImageId: '55614156379db324675650213bb544a8',
			locality: 'Near Ballygunge Station',
			areaName: 'Kasba',
			costForTwo: '₹350 for two',
			cuisines: ['Biryani', 'Mughlai', 'Kebabs'],
			avgRating: 4.4,
			parentId: '7461',
			avgRatingString: '4.4',
			totalRatingsString: '10K+',
			sla: {
				deliveryTime: 25,
				lastMileTravel: 1.2,
				serviceability: 'SERVICEABLE',
				slaString: '20-25 mins',
				lastMileTravelString: '1.2 km',
				iconType: 'ICON_TYPE_EMPTY',
			},
			availability: {
				nextCloseTime: '2024-03-17 04:00:00',
				opened: true,
			},
			badges: {},
			isOpen: true,
			type: 'F',
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			aggregatedDiscountInfoV3: {
				header: '₹125 OFF',
				subHeader: 'ABOVE ₹249',
				discountTag: 'FLAT DEAL',
			},
			differentiatedUi: {
				displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
				differentiatedUiMediaDetails: {
					mediaType: 'ADS_MEDIA_ENUM_IMAGE',
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
			restaurantOfferPresentationInfo: {},
		},
		analytics: {},
		cta: {
			link: 'https://www.swiggy.com/restaurants/the-biryani-inc-by-eatverse-near-ballygunge-station-kasba-kolkata-77719',
			type: 'WEBLINK',
		},
	},
	{
		info: {
			id: '112767',
			name: 'Tea Junction',
			cloudinaryImageId: '77d2fffe27cd59af5045a102d08af522',
			locality: 'Lake Road',
			areaName: 'Ballygunge',
			costForTwo: '₹150 for two',
			cuisines: ['Beverages', 'Snacks', 'Desserts'],
			avgRating: 4.5,
			parentId: '4311',
			avgRatingString: '4.5',
			totalRatingsString: '5K+',
			sla: {
				deliveryTime: 25,
				lastMileTravel: 3,
				serviceability: 'SERVICEABLE',
				slaString: '20-25 mins',
				lastMileTravelString: '3.0 km',
				iconType: 'ICON_TYPE_EMPTY',
			},
			availability: {
				nextCloseTime: '2024-03-17 05:00:00',
				opened: true,
			},
			badges: {},
			isOpen: true,
			type: 'F',
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			aggregatedDiscountInfoV3: {
				header: '40% OFF',
				subHeader: 'UPTO ₹80',
			},
			differentiatedUi: {
				displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
				differentiatedUiMediaDetails: {
					mediaType: 'ADS_MEDIA_ENUM_IMAGE',
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
			restaurantOfferPresentationInfo: {},
		},
		analytics: {},
		cta: {
			link: 'https://www.swiggy.com/restaurants/tea-junction-lake-road-ballygunge-kolkata-112767',
			type: 'WEBLINK',
		},
	},
	{
		info: {
			id: '8914',
			name: 'Subway',
			cloudinaryImageId: '63178e3e64d503a479f2a2048a474552',
			locality: 'Ruby',
			areaName: 'East Kolkata Township',
			costForTwo: '₹350 for two',
			cuisines: ['Healthy Food', 'Salads', 'Snacks', 'Desserts', 'Beverages'],
			avgRating: 4.4,
			parentId: '2',
			avgRatingString: '4.4',
			totalRatingsString: '10K+',
			sla: {
				deliveryTime: 30,
				lastMileTravel: 2,
				serviceability: 'SERVICEABLE',
				slaString: '30-35 mins',
				lastMileTravelString: '2.0 km',
				iconType: 'ICON_TYPE_EMPTY',
			},
			availability: {
				nextCloseTime: '2024-03-17 05:00:00',
				opened: true,
			},
			badges: {},
			isOpen: true,
			aggregatedDiscountInfoV2: {},
			type: 'F',
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			differentiatedUi: {
				displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
				differentiatedUiMediaDetails: {
					mediaType: 'ADS_MEDIA_ENUM_IMAGE',
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
			restaurantOfferPresentationInfo: {},
		},
		analytics: {},
		cta: {
			link: 'https://www.swiggy.com/restaurants/subway-ruby-east-kolkata-township-kolkata-8914',
			type: 'WEBLINK',
		},
	},
	{
		info: {
			id: '407661',
			name: 'Burger King',
			cloudinaryImageId: 'e33e1d3ba7d6b2bb0d45e1001b731fcf',
			locality: 'New Market',
			areaName: 'Esplanade',
			costForTwo: '₹350 for two',
			cuisines: ['Burgers', 'American'],
			avgRating: 4.2,
			parentId: '166',
			avgRatingString: '4.2',
			totalRatingsString: '10K+',
			sla: {
				deliveryTime: 42,
				lastMileTravel: 7.5,
				serviceability: 'SERVICEABLE',
				slaString: '40-45 mins',
				lastMileTravelString: '7.5 km',
				iconType: 'ICON_TYPE_EMPTY',
			},
			availability: {
				nextCloseTime: '2024-03-17 06:00:00',
				opened: true,
			},
			badges: {},
			isOpen: true,
			type: 'F',
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			aggregatedDiscountInfoV3: {
				header: '60% OFF',
				subHeader: 'UPTO ₹120',
			},
			differentiatedUi: {
				displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
				differentiatedUiMediaDetails: {
					mediaType: 'ADS_MEDIA_ENUM_IMAGE',
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
			restaurantOfferPresentationInfo: {},
		},
		analytics: {},
		cta: {
			link: 'https://www.swiggy.com/restaurants/burger-king-new-market-esplanade-kolkata-407661',
			type: 'WEBLINK',
		},
	},
	{
		info: {
			id: '364444',
			name: 'Pizza Hut',
			cloudinaryImageId: '2b4f62d606d1b2bfba9ba9e5386fabb7',
			locality: 'Garia Road',
			areaName: 'Ramkrishna Nagar',
			costForTwo: '₹350 for two',
			cuisines: ['Pizzas'],
			avgRating: 4.3,
			parentId: '721',
			avgRatingString: '4.3',
			totalRatingsString: '5K+',
			sla: {
				deliveryTime: 46,
				lastMileTravel: 8.4,
				serviceability: 'SERVICEABLE',
				slaString: '45-50 mins',
				lastMileTravelString: '8.4 km',
				iconType: 'ICON_TYPE_EMPTY',
			},
			availability: {
				nextCloseTime: '2024-03-17 04:00:00',
				opened: true,
			},
			badges: {},
			isOpen: true,
			type: 'F',
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			aggregatedDiscountInfoV3: {
				header: 'ITEMS',
				subHeader: 'AT ₹179',
			},
			differentiatedUi: {
				displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
				differentiatedUiMediaDetails: {
					mediaType: 'ADS_MEDIA_ENUM_IMAGE',
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
			restaurantOfferPresentationInfo: {},
		},
		analytics: {},
		cta: {
			link: 'https://www.swiggy.com/restaurants/pizza-hut-garia-road-ramkrishna-nagar-kolkata-364444',
			type: 'WEBLINK',
		},
	},
	{
		info: {
			id: '19117',
			name: 'Cafe Coffee Day',
			cloudinaryImageId: 'b70c7d23d197251b7b315b7e4d8173ae',
			locality: 'Joka',
			areaName: 'Ballygunge',
			costForTwo: '₹400 for two',
			cuisines: [
				'Beverages',
				'Cafe',
				'Snacks',
				'Desserts',
				'Burgers',
				'Ice Cream',
				'Bakery',
				'Fast Food',
			],
			avgRating: 4.5,
			parentId: '1',
			avgRatingString: '4.5',
			totalRatingsString: '1K+',
			sla: {
				deliveryTime: 23,
				lastMileTravel: 2.2,
				serviceability: 'SERVICEABLE',
				slaString: '20-25 mins',
				lastMileTravelString: '2.2 km',
				iconType: 'ICON_TYPE_EMPTY',
			},
			availability: {
				nextCloseTime: '2024-03-24 00:00:00',
				opened: true,
			},
			badges: {},
			isOpen: true,
			type: 'F',
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			aggregatedDiscountInfoV3: {
				header: '50% OFF',
				subHeader: 'UPTO ₹100',
			},
			differentiatedUi: {
				displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
				differentiatedUiMediaDetails: {
					mediaType: 'ADS_MEDIA_ENUM_IMAGE',
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
			restaurantOfferPresentationInfo: {},
		},
		analytics: {},
		cta: {
			link: 'https://www.swiggy.com/restaurants/cafe-coffee-day-joka-ballygunge-kolkata-19117',
			type: 'WEBLINK',
		},
	},
	{
		info: {
			id: '32302',
			name: 'Keventers - Milkshakes & Desserts',
			cloudinaryImageId: '1c8517dc925655dfff4d3617bd2191a5',
			locality: 'Sarat bose road',
			areaName: 'Sarat Bose Road',
			costForTwo: '₹200 for two',
			cuisines: ['Beverages', 'Ice Cream', 'Desserts', 'Healthy Food'],
			avgRating: 4.4,
			veg: true,
			parentId: '268997',
			avgRatingString: '4.4',
			totalRatingsString: '10K+',
			sla: {
				deliveryTime: 28,
				lastMileTravel: 4.5,
				serviceability: 'SERVICEABLE',
				slaString: '25-30 mins',
				lastMileTravelString: '4.5 km',
				iconType: 'ICON_TYPE_EMPTY',
			},
			availability: {
				nextCloseTime: '2024-03-17 05:00:00',
				opened: true,
			},
			badges: {},
			isOpen: true,
			type: 'F',
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			aggregatedDiscountInfoV3: {
				header: '50% OFF',
				subHeader: 'UPTO ₹100',
			},
			differentiatedUi: {
				displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
				differentiatedUiMediaDetails: {
					mediaType: 'ADS_MEDIA_ENUM_IMAGE',
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
			restaurantOfferPresentationInfo: {},
		},
		analytics: {},
		cta: {
			link: 'https://www.swiggy.com/restaurants/keventers-milkshakes-and-desserts-sarat-bose-road-kolkata-32302',
			type: 'WEBLINK',
		},
	},
	{
		info: {
			id: '17602',
			name: "Don Giovanni's",
			cloudinaryImageId: 'dldatsfuylpxgkieqfpk',
			locality: 'Park Street',
			areaName: 'Park Street',
			costForTwo: '₹1300 for two',
			cuisines: ['Chinese', 'Italian', 'Pizzas', 'Thai'],
			avgRating: 4.1,
			parentId: '6196',
			avgRatingString: '4.1',
			totalRatingsString: '5K+',
			sla: {
				deliveryTime: 42,
				lastMileTravel: 6.7,
				serviceability: 'SERVICEABLE',
				slaString: '40-45 mins',
				lastMileTravelString: '6.7 km',
				iconType: 'ICON_TYPE_EMPTY',
			},
			availability: {
				nextCloseTime: '2024-03-17 03:36:00',
				opened: true,
			},
			badges: {},
			isOpen: true,
			type: 'F',
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			aggregatedDiscountInfoV3: {
				header: '60% OFF',
				subHeader: 'UPTO ₹120',
			},
			differentiatedUi: {
				displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
				differentiatedUiMediaDetails: {
					mediaType: 'ADS_MEDIA_ENUM_IMAGE',
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
			restaurantOfferPresentationInfo: {},
		},
		analytics: {},
		cta: {
			link: 'https://www.swiggy.com/restaurants/don-giovannis-park-street-kolkata-17602',
			type: 'WEBLINK',
		},
	},
	{
		info: {
			id: '207635',
			name: 'Wow! Momo',
			cloudinaryImageId: '64fd45fd9f44c1737bc446e470bed666',
			locality: 'Sahid Khudiram Metro Station',
			areaName: 'Garia',
			costForTwo: '₹300 for two',
			cuisines: [
				'Tibetan',
				'Healthy Food',
				'Asian',
				'Chinese',
				'Snacks',
				'Continental',
				'Desserts',
				'Beverages',
			],
			avgRating: 4.5,
			parentId: '1776',
			avgRatingString: '4.5',
			totalRatingsString: '500+',
			sla: {
				deliveryTime: 40,
				lastMileTravel: 7.4,
				serviceability: 'SERVICEABLE',
				slaString: '40-45 mins',
				lastMileTravelString: '7.4 km',
				iconType: 'ICON_TYPE_EMPTY',
			},
			availability: {
				nextCloseTime: '2024-03-17 09:00:00',
				opened: true,
			},
			badges: {},
			isOpen: true,
			type: 'F',
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			aggregatedDiscountInfoV3: {
				header: '60% OFF',
				subHeader: 'UPTO ₹120',
			},
			differentiatedUi: {
				displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
				differentiatedUiMediaDetails: {
					mediaType: 'ADS_MEDIA_ENUM_IMAGE',
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
			restaurantOfferPresentationInfo: {},
		},
		analytics: {},
		cta: {
			link: 'https://www.swiggy.com/restaurants/wow-momo-sahid-khudiram-metro-station-garia-kolkata-207635',
			type: 'WEBLINK',
		},
	},
	{
		info: {
			id: '168808',
			name: 'Kung Pao By Don Gio',
			cloudinaryImageId: 'mue5x1il1yq4e5oss2hz',
			locality: 'Next to Bypass Dhaba',
			areaName: 'Science City',
			costForTwo: '₹1000 for two',
			cuisines: ['Chinese', 'Thai', 'Burmese', 'Indonesian'],
			avgRating: 4,
			parentId: '472176',
			avgRatingString: '4.0',
			totalRatingsString: '100+',
			sla: {
				deliveryTime: 39,
				lastMileTravel: 5.8,
				serviceability: 'SERVICEABLE',
				slaString: '35-40 mins',
				lastMileTravelString: '5.8 km',
				iconType: 'ICON_TYPE_EMPTY',
			},
			availability: {
				nextCloseTime: '2024-03-17 03:40:00',
				opened: true,
			},
			badges: {},
			isOpen: true,
			type: 'F',
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			aggregatedDiscountInfoV3: {
				header: '60% OFF',
				subHeader: 'UPTO ₹120',
			},
			differentiatedUi: {
				displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
				differentiatedUiMediaDetails: {
					mediaType: 'ADS_MEDIA_ENUM_IMAGE',
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
			restaurantOfferPresentationInfo: {},
		},
		analytics: {},
		cta: {
			link: 'https://www.swiggy.com/restaurants/kung-pao-by-don-gio-next-to-bypass-dhaba-science-city-kolkata-168808',
			type: 'WEBLINK',
		},
	},
	{
		info: {
			id: '83489',
			name: 'UDDTA PUNJAB by DON GIOVANNIS',
			cloudinaryImageId: 'acylm9wfd11hj8vjouif',
			locality: 'Taltala',
			areaName: 'Parkstreet',
			costForTwo: '₹1000 for two',
			cuisines: ['Indian', 'Chinese'],
			avgRating: 3.8,
			parentId: '218923',
			avgRatingString: '3.8',
			totalRatingsString: '500+',
			sla: {
				deliveryTime: 45,
				lastMileTravel: 6.7,
				serviceability: 'SERVICEABLE',
				slaString: '40-45 mins',
				lastMileTravelString: '6.7 km',
				iconType: 'ICON_TYPE_EMPTY',
			},
			availability: {
				nextCloseTime: '2024-03-17 03:36:00',
				opened: true,
			},
			badges: {
				imageBadges: [
					{
						imageId: 'newg.png',
						description: 'Gourmet',
					},
				],
			},
			isOpen: true,
			type: 'F',
			badgesV2: {
				entityBadges: {
					imageBased: {
						badgeObject: [
							{
								attributes: {
									description: 'Gourmet',
									imageId: 'newg.png',
								},
							},
						],
					},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			aggregatedDiscountInfoV3: {
				header: '60% OFF',
				subHeader: 'UPTO ₹120',
			},
			differentiatedUi: {
				displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
				differentiatedUiMediaDetails: {
					mediaType: 'ADS_MEDIA_ENUM_IMAGE',
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
			restaurantOfferPresentationInfo: {},
		},
		analytics: {},
		cta: {
			link: 'https://www.swiggy.com/restaurants/uddta-punjab-by-don-giovannis-taltala-parkstreet-kolkata-83489',
			type: 'WEBLINK',
		},
	},
	{
		info: {
			id: '211934',
			name: 'Machhli Baba Fries',
			cloudinaryImageId: 'bnwtkkytkiil9ynm2dn1',
			locality: 'Vivekananda Park',
			areaName: 'Santoshpur',
			costForTwo: '₹250 for two',
			cuisines: [
				'Bengali',
				'Street Food',
				'Rolls & Wraps',
				'Kebabs',
				'Fast Food',
			],
			avgRating: 4.5,
			parentId: '4413',
			avgRatingString: '4.5',
			totalRatingsString: '5K+',
			sla: {
				deliveryTime: 36,
				lastMileTravel: 5,
				serviceability: 'SERVICEABLE',
				slaString: '35-40 mins',
				lastMileTravelString: '5.0 km',
				iconType: 'ICON_TYPE_EMPTY',
			},
			availability: {
				nextCloseTime: '2024-03-17 04:00:00',
				opened: true,
			},
			badges: {},
			isOpen: true,
			type: 'F',
			badgesV2: {
				entityBadges: {
					imageBased: {},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			aggregatedDiscountInfoV3: {
				header: '20% OFF',
				subHeader: 'UPTO ₹50',
			},
			differentiatedUi: {
				displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
				differentiatedUiMediaDetails: {
					mediaType: 'ADS_MEDIA_ENUM_IMAGE',
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
			restaurantOfferPresentationInfo: {},
		},
		analytics: {},
		cta: {
			link: 'https://www.swiggy.com/restaurants/machhli-baba-fries-vivekananda-park-santoshpur-kolkata-211934',
			type: 'WEBLINK',
		},
	},
	{
		info: {
			id: '12454',
			name: 'The Bridge - The Park',
			cloudinaryImageId: 'vi07pwo1ifyekoj8cktv',
			locality: 'Park Street',
			areaName: 'Taltala',
			costForTwo: '₹1100 for two',
			cuisines: [
				'North Indian',
				'Chinese',
				'Japanese',
				'American',
				'Continental',
				'Italian',
				'Bengali',
				'Thai',
			],
			avgRating: 4.3,
			parentId: '21696',
			avgRatingString: '4.3',
			totalRatingsString: '100+',
			sla: {
				deliveryTime: 52,
				lastMileTravel: 7,
				serviceability: 'SERVICEABLE',
				slaString: '50-55 mins',
				lastMileTravelString: '7.0 km',
				iconType: 'ICON_TYPE_EMPTY',
			},
			availability: {
				nextCloseTime: '2024-03-17 05:00:00',
				opened: true,
			},
			badges: {
				imageBadges: [
					{
						imageId: 'newg.png',
						description: 'Gourmet',
					},
				],
			},
			isOpen: true,
			aggregatedDiscountInfoV2: {},
			type: 'F',
			badgesV2: {
				entityBadges: {
					imageBased: {
						badgeObject: [
							{
								attributes: {
									description: 'Gourmet',
									imageId: 'newg.png',
								},
							},
						],
					},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			differentiatedUi: {
				displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
				differentiatedUiMediaDetails: {
					mediaType: 'ADS_MEDIA_ENUM_IMAGE',
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
			restaurantOfferPresentationInfo: {},
		},
		analytics: {},
		cta: {
			link: 'https://www.swiggy.com/restaurants/the-bridge-the-park-park-street-taltala-kolkata-12454',
			type: 'WEBLINK',
		},
	},
	{
		info: {
			id: '349735',
			name: 'Bianco',
			cloudinaryImageId: '5450bebc7a36864446d053401e499d34',
			locality: 'Borough- Viii',
			areaName: 'Ballygunge',
			costForTwo: '₹900 for two',
			cuisines: [
				'Continental',
				'Pan-Asian',
				'Chinese',
				'Beverages',
				'Pastas',
				'Pizzas',
				'Italian',
			],
			avgRating: 4.1,
			parentId: '358790',
			avgRatingString: '4.1',
			totalRatingsString: '100+',
			sla: {
				deliveryTime: 29,
				lastMileTravel: 2.2,
				serviceability: 'SERVICEABLE',
				slaString: '25-30 mins',
				lastMileTravelString: '2.2 km',
				iconType: 'ICON_TYPE_EMPTY',
			},
			availability: {
				nextCloseTime: '2024-03-17 22:00:00',
				opened: true,
			},
			badges: {
				imageBadges: [
					{
						imageId: 'newg.png',
						description: 'Gourmet',
					},
				],
			},
			isOpen: true,
			type: 'F',
			badgesV2: {
				entityBadges: {
					imageBased: {
						badgeObject: [
							{
								attributes: {
									description: 'Gourmet',
									imageId: 'newg.png',
								},
							},
						],
					},
					textBased: {},
					textExtendedBadges: {},
				},
			},
			aggregatedDiscountInfoV3: {
				header: '50% OFF',
				subHeader: 'UPTO ₹100',
			},
			differentiatedUi: {
				displayType: 'ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT',
				differentiatedUiMediaDetails: {
					mediaType: 'ADS_MEDIA_ENUM_IMAGE',
					lottie: {},
					video: {},
				},
			},
			reviewsSummary: {},
			displayType: 'RESTAURANT_DISPLAY_TYPE_DEFAULT',
			restaurantOfferPresentationInfo: {},
		},
		analytics: {},
		cta: {
			link: 'https://www.swiggy.com/restaurants/bianco-borough-viii-ballygunge-kolkata-349735',
			type: 'WEBLINK',
		},
	},
];
export default resList;
